# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yikv

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PutBatchResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PutBatchResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPutBatchResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PutBatchResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PutBatchResponse
    def Ok(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PutBatchResponse
    def Err(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PutBatchResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    PutBatchResponseStart(builder)

def PutBatchResponseAddOk(builder, ok):
    builder.PrependBoolSlot(0, ok, 0)

def AddOk(builder, ok):
    PutBatchResponseAddOk(builder, ok)

def PutBatchResponseAddErr(builder, err):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(err), 0)

def AddErr(builder, err):
    PutBatchResponseAddErr(builder, err)

def PutBatchResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return PutBatchResponseEnd(builder)
