# automatically generated by the FlatBuffers compiler, do not modify

# namespace: yikv

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PutRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PutRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPutRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PutRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PutRequest
    def Row(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from yikv.Row import Row
            obj = Row()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PutRequest
    def TableName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PutRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    PutRequestStart(builder)

def PutRequestAddRow(builder, row):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(row), 0)

def AddRow(builder, row):
    PutRequestAddRow(builder, row)

def PutRequestAddTableName(builder, tableName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tableName), 0)

def AddTableName(builder, tableName):
    PutRequestAddTableName(builder, tableName)

def PutRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return PutRequestEnd(builder)
