// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BatchGetRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BatchGetRequest getRootAsBatchGetRequest(ByteBuffer _bb) { return getRootAsBatchGetRequest(_bb, new BatchGetRequest()); }
  public static BatchGetRequest getRootAsBatchGetRequest(ByteBuffer _bb, BatchGetRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BatchGetRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pks(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int pksLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector pksVector() { return pksVector(new StringVector()); }
  public StringVector pksVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String tableName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tableNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer tableNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createBatchGetRequest(FlatBufferBuilder builder,
      int pksOffset,
      int tableNameOffset) {
    builder.startTable(2);
    BatchGetRequest.addTableName(builder, tableNameOffset);
    BatchGetRequest.addPks(builder, pksOffset);
    return BatchGetRequest.endBatchGetRequest(builder);
  }

  public static void startBatchGetRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPks(FlatBufferBuilder builder, int pksOffset) { builder.addOffset(0, pksOffset, 0); }
  public static int createPksVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTableName(FlatBufferBuilder builder, int tableNameOffset) { builder.addOffset(1, tableNameOffset, 0); }
  public static int endBatchGetRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BatchGetRequest get(int j) { return get(new BatchGetRequest(), j); }
    public BatchGetRequest get(BatchGetRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

