// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldValue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static FieldValue getRootAsFieldValue(ByteBuffer _bb) { return getRootAsFieldValue(_bb, new FieldValue()); }
  public static FieldValue getRootAsFieldValue(ByteBuffer _bb, FieldValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int fieldId() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }
  public int vtype() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public int i32() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long i64() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public float f32() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public double f64() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public String s() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer sAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer sInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public int raw(int j) { int o = __offset(18); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int rawLength() { int o = __offset(18); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector rawVector() { return rawVector(new ByteVector()); }
  public ByteVector rawVector(ByteVector obj) { int o = __offset(18); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer rawAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer rawInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public int ai32(int j) { int o = __offset(20); return o != 0 ? bb.getInt(__vector(o) + j * 4) : 0; }
  public int ai32Length() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public IntVector ai32Vector() { return ai32Vector(new IntVector()); }
  public IntVector ai32Vector(IntVector obj) { int o = __offset(20); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer ai32AsByteBuffer() { return __vector_as_bytebuffer(20, 4); }
  public ByteBuffer ai32InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 4); }
  public long ai64(int j) { int o = __offset(22); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int ai64Length() { int o = __offset(22); return o != 0 ? __vector_len(o) : 0; }
  public LongVector ai64Vector() { return ai64Vector(new LongVector()); }
  public LongVector ai64Vector(LongVector obj) { int o = __offset(22); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer ai64AsByteBuffer() { return __vector_as_bytebuffer(22, 8); }
  public ByteBuffer ai64InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 22, 8); }
  public float af32(int j) { int o = __offset(24); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int af32Length() { int o = __offset(24); return o != 0 ? __vector_len(o) : 0; }
  public FloatVector af32Vector() { return af32Vector(new FloatVector()); }
  public FloatVector af32Vector(FloatVector obj) { int o = __offset(24); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer af32AsByteBuffer() { return __vector_as_bytebuffer(24, 4); }
  public ByteBuffer af32InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 4); }
  public double af64(int j) { int o = __offset(26); return o != 0 ? bb.getDouble(__vector(o) + j * 8) : 0; }
  public int af64Length() { int o = __offset(26); return o != 0 ? __vector_len(o) : 0; }
  public DoubleVector af64Vector() { return af64Vector(new DoubleVector()); }
  public DoubleVector af64Vector(DoubleVector obj) { int o = __offset(26); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer af64AsByteBuffer() { return __vector_as_bytebuffer(26, 8); }
  public ByteBuffer af64InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 8); }
  public String as(int j) { int o = __offset(28); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int asLength() { int o = __offset(28); return o != 0 ? __vector_len(o) : 0; }
  public StringVector asVector() { return asVector(new StringVector()); }
  public StringVector asVector(StringVector obj) { int o = __offset(28); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  /**
   * Logical column name from table schema (optional on write; server sets on read paths).
   */
  public String fieldName() { int o = __offset(30); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fieldNameAsByteBuffer() { return __vector_as_bytebuffer(30, 1); }
  public ByteBuffer fieldNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 30, 1); }

  public static int createFieldValue(FlatBufferBuilder builder,
      int fieldId,
      int vtype,
      int i32,
      long i64,
      float f32,
      double f64,
      int sOffset,
      int rawOffset,
      int ai32Offset,
      int ai64Offset,
      int af32Offset,
      int af64Offset,
      int asOffset,
      int fieldNameOffset) {
    builder.startTable(14);
    FieldValue.addF64(builder, f64);
    FieldValue.addI64(builder, i64);
    FieldValue.addFieldName(builder, fieldNameOffset);
    FieldValue.addAs(builder, asOffset);
    FieldValue.addAf64(builder, af64Offset);
    FieldValue.addAf32(builder, af32Offset);
    FieldValue.addAi64(builder, ai64Offset);
    FieldValue.addAi32(builder, ai32Offset);
    FieldValue.addRaw(builder, rawOffset);
    FieldValue.addS(builder, sOffset);
    FieldValue.addF32(builder, f32);
    FieldValue.addI32(builder, i32);
    FieldValue.addFieldId(builder, fieldId);
    FieldValue.addVtype(builder, vtype);
    return FieldValue.endFieldValue(builder);
  }

  public static void startFieldValue(FlatBufferBuilder builder) { builder.startTable(14); }
  public static void addFieldId(FlatBufferBuilder builder, int fieldId) { builder.addShort(0, (short) fieldId, (short) 0); }
  public static void addVtype(FlatBufferBuilder builder, int vtype) { builder.addByte(1, (byte) vtype, (byte) 0); }
  public static void addI32(FlatBufferBuilder builder, int i32) { builder.addInt(2, i32, 0); }
  public static void addI64(FlatBufferBuilder builder, long i64) { builder.addLong(3, i64, 0L); }
  public static void addF32(FlatBufferBuilder builder, float f32) { builder.addFloat(4, f32, 0.0f); }
  public static void addF64(FlatBufferBuilder builder, double f64) { builder.addDouble(5, f64, 0.0); }
  public static void addS(FlatBufferBuilder builder, int sOffset) { builder.addOffset(6, sOffset, 0); }
  public static void addRaw(FlatBufferBuilder builder, int rawOffset) { builder.addOffset(7, rawOffset, 0); }
  public static int createRawVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createRawVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startRawVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addAi32(FlatBufferBuilder builder, int ai32Offset) { builder.addOffset(8, ai32Offset, 0); }
  public static int createAi32Vector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startAi32Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAi64(FlatBufferBuilder builder, int ai64Offset) { builder.addOffset(9, ai64Offset, 0); }
  public static int createAi64Vector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startAi64Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addAf32(FlatBufferBuilder builder, int af32Offset) { builder.addOffset(10, af32Offset, 0); }
  public static int createAf32Vector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startAf32Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addAf64(FlatBufferBuilder builder, int af64Offset) { builder.addOffset(11, af64Offset, 0); }
  public static int createAf64Vector(FlatBufferBuilder builder, double[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addDouble(data[i]); return builder.endVector(); }
  public static void startAf64Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addAs(FlatBufferBuilder builder, int asOffset) { builder.addOffset(12, asOffset, 0); }
  public static int createAsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startAsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addFieldName(FlatBufferBuilder builder, int fieldNameOffset) { builder.addOffset(13, fieldNameOffset, 0); }
  public static int endFieldValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldValue get(int j) { return get(new FieldValue(), j); }
    public FieldValue get(FieldValue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

