// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetResponse getRootAsGetResponse(ByteBuffer _bb) { return getRootAsGetResponse(_bb, new GetResponse()); }
  public static GetResponse getRootAsGetResponse(ByteBuffer _bb, GetResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean found() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String err() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer errInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public yikv.Row row() { return row(new yikv.Row()); }
  public yikv.Row row(yikv.Row obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long indexGetNs() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createGetResponse(FlatBufferBuilder builder,
      boolean found,
      int errOffset,
      int rowOffset,
      long indexGetNs) {
    builder.startTable(4);
    GetResponse.addIndexGetNs(builder, indexGetNs);
    GetResponse.addRow(builder, rowOffset);
    GetResponse.addErr(builder, errOffset);
    GetResponse.addFound(builder, found);
    return GetResponse.endGetResponse(builder);
  }

  public static void startGetResponse(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addFound(FlatBufferBuilder builder, boolean found) { builder.addBoolean(0, found, false); }
  public static void addErr(FlatBufferBuilder builder, int errOffset) { builder.addOffset(1, errOffset, 0); }
  public static void addRow(FlatBufferBuilder builder, int rowOffset) { builder.addOffset(2, rowOffset, 0); }
  public static void addIndexGetNs(FlatBufferBuilder builder, long indexGetNs) { builder.addLong(3, indexGetNs, 0L); }
  public static int endGetResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetResponse get(int j) { return get(new GetResponse(), j); }
    public GetResponse get(GetResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

