// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetRequest getRootAsGetRequest(ByteBuffer _bb) { return getRootAsGetRequest(_bb, new GetRequest()); }
  public static GetRequest getRootAsGetRequest(ByteBuffer _bb, GetRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String pk() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pkAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer pkInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String tableName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tableNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer tableNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createGetRequest(FlatBufferBuilder builder,
      int pkOffset,
      int tableNameOffset) {
    builder.startTable(2);
    GetRequest.addTableName(builder, tableNameOffset);
    GetRequest.addPk(builder, pkOffset);
    return GetRequest.endGetRequest(builder);
  }

  public static void startGetRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPk(FlatBufferBuilder builder, int pkOffset) { builder.addOffset(0, pkOffset, 0); }
  public static void addTableName(FlatBufferBuilder builder, int tableNameOffset) { builder.addOffset(1, tableNameOffset, 0); }
  public static int endGetRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // pk
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetRequest get(int j) { return get(new GetRequest(), j); }
    public GetRequest get(GetRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

