// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PutBatchRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static PutBatchRequest getRootAsPutBatchRequest(ByteBuffer _bb) { return getRootAsPutBatchRequest(_bb, new PutBatchRequest()); }
  public static PutBatchRequest getRootAsPutBatchRequest(ByteBuffer _bb, PutBatchRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PutBatchRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public yikv.Row rows(int j) { return rows(new yikv.Row(), j); }
  public yikv.Row rows(yikv.Row obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int rowsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public yikv.Row.Vector rowsVector() { return rowsVector(new yikv.Row.Vector()); }
  public yikv.Row.Vector rowsVector(yikv.Row.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String tableName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tableNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer tableNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createPutBatchRequest(FlatBufferBuilder builder,
      int rowsOffset,
      int tableNameOffset) {
    builder.startTable(2);
    PutBatchRequest.addTableName(builder, tableNameOffset);
    PutBatchRequest.addRows(builder, rowsOffset);
    return PutBatchRequest.endPutBatchRequest(builder);
  }

  public static void startPutBatchRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRows(FlatBufferBuilder builder, int rowsOffset) { builder.addOffset(0, rowsOffset, 0); }
  public static int createRowsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRowsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTableName(FlatBufferBuilder builder, int tableNameOffset) { builder.addOffset(1, tableNameOffset, 0); }
  public static int endPutBatchRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // rows
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PutBatchRequest get(int j) { return get(new PutBatchRequest(), j); }
    public PutBatchRequest get(PutBatchRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

