// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class PutResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static PutResponse getRootAsPutResponse(ByteBuffer _bb) { return getRootAsPutResponse(_bb, new PutResponse()); }
  public static PutResponse getRootAsPutResponse(ByteBuffer _bb, PutResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public PutResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean ok() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String err() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer errInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createPutResponse(FlatBufferBuilder builder,
      boolean ok,
      int errOffset) {
    builder.startTable(2);
    PutResponse.addErr(builder, errOffset);
    PutResponse.addOk(builder, ok);
    return PutResponse.endPutResponse(builder);
  }

  public static void startPutResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addOk(FlatBufferBuilder builder, boolean ok) { builder.addBoolean(0, ok, false); }
  public static void addErr(FlatBufferBuilder builder, int errOffset) { builder.addOffset(1, errOffset, 0); }
  public static int endPutResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public PutResponse get(int j) { return get(new PutResponse(), j); }
    public PutResponse get(PutResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

