// automatically generated by the FlatBuffers compiler, do not modify

package yikv;

@SuppressWarnings("unused")
public final class ValueType {
  private ValueType() { }
  public static final int NONE = 0;
  public static final int BOOL = 1;
  public static final int I32 = 2;
  public static final int I64 = 3;
  public static final int F32 = 4;
  public static final int F64 = 5;
  public static final int STRING = 6;
  public static final int BYTES = 7;
  public static final int ARR_I32 = 8;
  public static final int ARR_I64 = 9;
  public static final int ARR_F32 = 10;
  public static final int ARR_F64 = 11;
  public static final int ARR_STRING = 12;

  public static final String[] names = { "NONE", "BOOL", "I32", "I64", "F32", "F64", "STRING", "BYTES", "ARR_I32", "ARR_I64", "ARR_F32", "ARR_F64", "ARR_STRING", };

  public static String name(int e) { return names[e]; }
}

