apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yikv

resources:
  - ../../base
  - statefulset.yaml
  - service-headless.yaml

patchesStrategicMerge:
  - delete-deployment.yaml
  - delete-pvc.yaml
